[workspace]
members = [
    "contracts/webauthn_verifier",
    "contracts/smart_account",
    "contracts/policy_engine",
    "contracts/intent_registry",
    "contracts/recovery_manager",
    "contracts/transfer_adapter",
    "contracts/split_adapter",
    "contracts/threshold_policy",
    "contracts/governance_account",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
soroban-sdk = { version = "26.1.0", features = ["experimental_spec_shaking_v2"] }
stellar-accounts = "0.7.2"
stellar-access = "0.7.2"
stellar-contract-utils = "0.7.2"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
